package udp.bidirecional;

import java.awt.event.KeyEvent;

import java.net.InetAddress;
import java.net.UnknownHostException;

public class ClienteServidorForm extends javax.swing.JFrame {

    private ClienteServidor app;

    public ClienteServidorForm() {
        initComponents();
        this.setTitle("Cliente Servidor");

        // app = new ClienteServidor()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHistorico = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblHost = new javax.swing.JLabel();
        txtHistoricoScroll = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        txtMensagem = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        txtPortaIn = new javax.swing.JTextField();
        lblPotaIn = new javax.swing.JLabel();
        txtPortaOut = new javax.swing.JTextField();
        lblPortaOut = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHistorico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHistorico.setText("Histórico");

        txtHost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        //txtHost.setText("172.25.3.37");
        
        /*Define o endereço IP*/
        
        try {
            // Obtendo o endereço IP da máquina local
            InetAddress localHost = InetAddress.getLocalHost();
            String ipAddress = localHost.getHostAddress();
            
            txtHost.setText(ipAddress);
        }catch (UnknownHostException e) {
            e.printStackTrace();
        }
        
        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        lblHost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHost.setText("Host");

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        txtHistoricoScroll.setViewportView(txtHistorico);

        txtMensagem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMensagemKeyReleased(evt);
            }
        });

        lblMensagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMensagem.setText("Mensagem");

        txtPortaIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPortaIn.setText("10003");

        lblPotaIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPotaIn.setText("Porta In");

        txtPortaOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPortaOut.setText("10004");

        lblPortaOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPortaOut.setText("Porta Out");

        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHistorico)
                    .addComponent(lblMensagem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHost)
                            .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPotaIn)
                            .addComponent(txtPortaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPortaOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPortaOut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStart))
                    .addComponent(txtMensagem)
                    .addComponent(txtHistoricoScroll))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHost)
                            .addComponent(lblPotaIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPortaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPortaOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPortaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHistoricoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensagemKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (app != null) {
                app.enviar(txtMensagem.getText());
                txtMensagem.setText("");
                txtMensagem.requestFocus();
            }
        }
    }//GEN-LAST:event_txtMensagemKeyReleased

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        app = new ClienteServidor(
                txtHost.getText(),
                Integer.parseInt(txtPortaIn.getText()),
                Integer.parseInt(txtPortaOut.getText()),
                txtHistorico
        );
        app.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteServidorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblHistorico;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblPortaOut;
    private javax.swing.JLabel lblPotaIn;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JScrollPane txtHistoricoScroll;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JTextField txtPortaIn;
    private javax.swing.JTextField txtPortaOut;
    // End of variables declaration//GEN-END:variables
}
